version: "3.7"

services:
  dynamo-db-api-dev:
    container_name: dynamo-db-api-dev
    image: dynamo-db-api-dev:0.1.0
    build:
      context: ..
      target: development
      dockerfile: docker/Dockerfile
    command: npm run start:dev
    ports:
      - 5000:80
    environment:
      - NODE_ENV=dev
      - APP_TITLE=DynamoDB API
      - APP_DESCRIPTION=NodeJS API using Dynamo DB
      - APP_VERSION=0.1.0
      - AWS_ACCESS_KEY_ID=AKIAWW34FLHYMJ5LMKBP
      - AWS_ACCESS_KEY_SECRET=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
      - AWS_REGION=us-east-1
      - AWS_URL=http://dynamodb-local:8000
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dynamo-db-api
    depends_on:
      - dynamodb-local

  dynamo-db-api-prod:
    container_name: dynamo-db-api-prod
    image: dynamo-db-api-prod:0.1.0
    build:
      context: ..
      target: production
      dockerfile: docker/Dockerfile
    command: npm run start:prod
    ports:
      - 4200:80
    environment:
      - NODE_ENV=prod
      - APP_TITLE=DynamoDB API
      - APP_DESCRIPTION=NodeJS API using Dynamo DB
      - APP_VERSION=0.1.0
      - AWS_ACCESS_KEY_ID=AKIAWW34FLHYMJ5LMKBP
      - AWS_ACCESS_KEY_SECRET=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
      - AWS_REGION=us-east-1
    volumes:
      - ..:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - dynamo-db-api

  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: "amazon/dynamodb-local:latest"
    build:
      context: ..
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - "../data:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal
    networks:
      - dynamo-db-api

networks:
  dynamo-db-api:
    external: true
